---
- name: install transmission-cli
  pacman:
    name: transmission-cli
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [torrent,transmission,transmission-cli]

- name: install transmission-remote-gtk
  pacman:
    name: transmission-remote-gtk
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [torrent,transmission,transmission-remote-gtk]

- name: install transmission (osx)
  homebrew_cask:
    name: transmission
  when: ansible_pkg_mgr == "homebrew"
  tags: [torrent,transmission]
