---
- name: install (apt)
  shell: echo install teiler; false
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,teiler]

- name: install (arch)
  pacaur:
    name: teiler-git
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,teiler]
