---
- name: install pass (arch)
  pacman:
    name: pass
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,pass]

- name: install gnupg (osx)
  homebrew:
    name: gnupg
  when: ansible_pkg_mgr == "homebrew"
  tags: [config-install,pass, gnupg]

- name: install pass (osx)
  homebrew:
    name: pass
  when: ansible_pkg_mgr == "homebrew"
  tags: [config-install,pass]
