---
- name: install ascii (apt)
  apt: name=ascii
  become: true
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,cli-extras,ascii]

- name: install ascii (arch)
  pacman:
    name: ascii
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,ascii]

- name: install ascii (osx)
  debug:
    msg: missing ascii {{ansible_pkg_mgr}}
  when: ansible_pkg_mgr == "homebrew"
  tags: [config-install,cli-extras,ascii]

- name: install asciinema (apt)
  apt:
    name: asciinema
  become: true
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,cli-extras,asciinema]

- name: install asciinema (arch)
  pacman:
    name: asciinema
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,asciinema]

- name: install asciinema (osx)
  debug:
    msg: missing asciinema {{ansible_pkg_mgr}}
  when: ansible_pkg_mgr == "homebrew"
  tags: [config-install,cli-extras,asciinema]

- name: install unzip (arch)
  pacman:
    name: unzip
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,unzip]

- name: install jq (arch)
  pacman:
    name: jq
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,jq]

- name: install dns-utils (arch)
  pacman:
    name: bind-tools
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,bind-tools]

- name: install wget (arch)
  pacman:
    name: wget
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,wget]

- name: install wget (osx)
  homebrew:
    name: wget
  when: ansible_pkg_mgr == "homebrew"
  tags: [config-install,cli-extras,wget]

- name: install vim (arch)
  pacman:
    name: vim
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,vim]

- name: install pwgen (arch)
  pacman:
    name: pwgen
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,pwgen]

- name: install graphviz (arch)
  pacman:
    name: graphviz
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,graphviz]

- name: install graphviz (osx)
  homebrew:
    name: graphviz
  when: ansible_pkg_mgr == "homebrew"
  tags: [config-install,cli-extras,graphviz]

- name: install dmidecode (arch)
  pacman:
    name: dmidecode
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,dmidecode]

- name: install heroku-cli (arch)
  pacaur:
    name: heroku-cli
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,heroku-cli]

- name: install bc (arch)
  pacman:
    name: bc
  when: ansible_pkg_mgr == "pacman"
  become: true
  tags: [config-install,cli-extras,bc]

- name: install ncdu (arch)
  pacaur:
    name: ncdu
  when: ansible_pkg_mgr == "pacman"
  become: true
  tags: [config-install,cli-extras,ncdu]
