---
- name: install ascii (apt)
  apt: name=ascii
  become: true
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,cli-extras,ascii]

- name: install ascii (arch)
  pacaur:
    name: community/ascii
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,ascii]

- name: install ascii (osx)
  shell: echo install ascii; false
  when: ansible_pkg_mgr == "homebrew"
  tags: [config-install,cli-extras,ascii]

- name: install asciinema (apt)
  apt:
    name: asciinema
  become: true
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,cli-extras,asciinema]

- name: install asciinema (arch)
  pacaur:
    name: community/asciinema
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,asciinema]

- name: install asciinema (osx)
  shell: echo install asciinema; false
  when: ansible_pkg_mgr == "homebrew"
  tags: [config-install,cli-extras,asciinema]

- name: install unzip (arch)
  pacaur:
    name: extra/unzip
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,unzip]

- name: install jq (arch)
  pacaur:
    name: community/jq
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,jq]

- name: install dns-utils (arch)
  pacaur:
    name: extra/bind-tools
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,bind-tools]

- name: install wget (arch)
  pacaur:
    name: extra/wget
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,wget]
