---
- name: install ascii (apt)
  apt: name=ascii
  become: true
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,cli-extras,ascii]

- name: install ascii (arch)
  pacaur:
    name: community/ascii
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,cli-extras,ascii]

- name: install ascii (osx)
  shell: echo install ascii; false
  when: ansible_pkg_mgr == "homebrew"
  tags: [config-install,cli-extras,ascii]
