[icons]
icons = "awesome4"

[theme]
theme = "solarized-dark"

[[block]]
block    = "battery"
# interval = 10
# driver   = "upower"
format   = " $icon $percentage "

# [[block]]
# block = "bluetooth"
# mac   = "E5:CC:3C:4E:F2:B0"
# label = ""

# [[block]]
# block = "bluetooth"
# mac   = "2C:41:A1:4C:BC:67"
# label = ""

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon   /: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"
interval = 1

# [[block]]
# block = "nvidia_gpu"
# show_temperature = true

[[block]]
block = "temperature"

[[block]]
block = "load"
interval = 1
#format = "{1m}"

[[block]]
block = "sound"

# [[block]]
# block = "time"
# interval = 60
# format = "%m/%d %I:%M"
[[block]]
block = "time"
interval = 60
[block.format]
#short = "$icon $timestamp.datetime(f:'%m/%d %I:%M') "
full  = "$icon $timestamp.datetime(f:'%m/%d %I:%M') "
