---

- import_playbook: config.yml

- hosts: all
  roles:
    - package-manager
    - browser
    - x
    - xcwd
    - teiler
    - i3
    - urxvt
    - fonts
    - rofi
    - polybar
    - desktop-productivity
    - slack
    - spotify
    - nvidia

# - polybar (broken)
# - fluxgui
