---
- import_playbook: config.yml

- hosts: all
  roles:
    - package-manager
    - fs-trim
    - docker
    - vagrant
    - cli-extras
    - zsh
    - homebrew
    - passwordstore
    - abconfig
    - git
    - go
    - node
    - fzf
    - neovim
    - rbenv
    - travis
    - awscli
    - ovrclk
    - pet
    - wrk
    - qemu
    - system-monitor
    - google-cloud
    - k8s-minikube
    - trezor
    - music
    - tex

- hosts: db
  roles:
    - postgres
    - redis

- hosts: ethereum-dev
  roles:
    - ethereum-dev

- hosts: ethereum-miner
  roles:
    - ethereum-miner

- hosts: bluetooth
  roles:
    - bluetooth
