---
- include: config.yml

- hosts: all
  roles:
    - package-manager
    - fs-trim
    - docker
    - postgres
    - redis
    - vagrant
    - cli-extras
    - zsh
    - homebrew
    - passwordstore
    - abconfig
    - git
    - go
    - fzf
    - neovim
    - rbenv
    - awscli
    - ovrclk
    - pet
    - wrk
