---
- import_playbook: config.yml

- hosts: all
  roles:
    - package-manager
    - python
    - ntp
    - fs-trim
    - docker
    - vagrant
    - cli-extras
    - zsh
    - passwordstore
    - abconfig
    - homebrew
    - git
    - go
    - node
    - fzf
    - neovim
    - rbenv
    # - travis
    # - pet
    - rust
    - wrk
    - qemu
    - system-monitor
    - google-cloud
    - k8s-minikube
    - trezor
    - music
    # - slack
    # - telegram
    - yubikey
    - keybase
    # - awscli
    # - bats
    # - terraform
    - media
    - shellcheck
    - yubikey-ssh
    - direnv
    - "1password"
    - rofi
    - podman

- hosts: osx
  roles:
    - osx

- hosts: db
  roles:
    - postgres
    - redis

- hosts: scheme-dev
  roles:
    - racket

- hosts: bluetooth
  roles:
    - bluetooth

- hosts: tex
  roles:
    - tex

- hosts: ledger
  roles:
    - ledger

- hosts: mandarin
  roles:
    - mandarin
