---
- include: config.yml

- hosts: all
  roles:
    - package-manager
    - fs-trim
    - passwordstore
    - zsh
    - abconfig
    - git
    - go
    - fzf
    - neovim
    - rbenv
    - awscli
    - ovrclk
    - pet
    - wrk
    - cli-extras
