---

- include: config.yml

- hosts: all
  tasks:
    - group_by: key=os_{{ansible_system | lower}}

- hosts: all
  roles:
    - package-manager
    - zsh
    - abconfig
    - git
    - go
    - fzf
    - neovim
    - rbenv
    - awscli
    - ovrclk
    - pet
    - wrk

- hosts: os_linux
  roles:
    - i3
