---
- include: config.yml

- hosts: all
  roles:
    - package-manager
    - fs-trim
    - docker
    - vagrant
    - cli-extras
    - zsh
    - homebrew
    - passwordstore
    - abconfig
    - git
    - go
    - fzf
    - neovim
    - rbenv
    - travis
    - awscli
    - ovrclk
    - pet
    - wrk
    - qemu
    - system-monitor
    - google-cloud

- hosts: db
  roles:
    - postgres
    - redis

- hosts: ethereum
  roles:
    - ethereum

- hosts: bluetooth
  roles:
    - bluetooth
