---
- name: install awscli (apt)
  apt: name={{item}}
  with_items:
    - awscli
  become: true
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,awscli]

- name: install awscli (arch)
  pacman:
    name: aws-cli
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,awscli]

# - name: configure shell environment vars
#   template: dest={{profiledir}}/50-awscli.sh
#             src=awscli.sh
#             mode=0600
#   tags: [config,awscli]

# - name: create aws conf dir
#   file: state=directory
#         path={{homedir}}/.aws
#         mode=0700
#   tags: [config,awscli]

# - name: write aws credentials
#   template: dest={{homedir}}/.aws/credentials
#             src=credentials
#             mode=0600
#   tags: [config,awscli]
