---
- name: install virtualbox
  pacaur:
    name: "{{item}}"
  with_items:
    - virtualbox
    - virtualbox-host-modules-arch
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,vagrant,virtualbox]

- name: install vagrant
  pacaur:
    name: vagrant
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,vagrant]
