---
- name: install virtualbox
  pacman:
    name: "{{item}}"
  with_items:
    - virtualbox
    - virtualbox-host-dkms
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,vagrant,virtualbox]

- name: install vagrant
  pacman:
    name: vagrant
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,vagrant]
