---
- name: install x utilities
  pacman: name={{item}}
  with_items:
    - xorg-xrandr
    - xorg-xev
    - xorg-xsetroot
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,x]
