---
- name: install x utilities
  pacman:
    name:
      - xorg
      - xorg-apps
      - xorg-xinit
      - xorg-xrandr
      - xorg-xev
      - xorg-xsetroot
      - xorg-server
      - xorg-docs
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,x]
