---

- name: install sysstat
  pacman:
    name: sysstat
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,system-monitor,sysstat]

- name: install glances
  pacman:
    name: "{{item}}"
  with_items:
    - glances
    - hddtemp
    - python-docker-py
    - python-matplotlib
    - python-netifaces
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,system-monitor,glances]

- name: install ctop
  pacaur:
    name: "{{item}}"
  with_items:
    - ctop
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,system-monitor,ctop]
