---

- name: install sysstat (aur)
  pacman:
    name: sysstat
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,system-monitor,sysstat]

- name: install glances (aur)
  pacman:
    name:
      - glances
      - hddtemp
      - python-docker-py
      - python-matplotlib
      - python-netifaces
  become: true
  when: false # FIXME ansible_pkg_mgr == "pacman"
  tags: [config-install,system-monitor,glances]

- name: install ctop (aur)
  pacaur:
    name: "{{item}}"
  with_items:
    - ctop
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,system-monitor,ctop]

- name: install lsof (aur)
  pacman:
    name: lsof
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,system-monitor,lsof]

- name: install htop (aur)
  pacman:
    name: htop
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,system-monitor,htop]

- name: install htop (osx)
  homebrew:
    name: htop
  when: ansible_pkg_mgr == "homebrew"
  tags: [config-install,system-monitor,htop]

- name: install i7z (aur)
  pacman:
    name: i7z
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [system-monitor,i7z]

- name: install hdparm (aur)
  pacman:
    name: hdparm
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [system-monitor,hdparm]

- name: install iperf3 (aur)
  pacman:
    name: iperf3
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [system-monitor,iperf3]

- name: install iperf3 (osx)
  homebrew:
    name: iperf3
  when: ansible_pkg_mgr == "homebrew"
  tags: [system-monitor,iperf3]
