---

- name: install anki (aur)
  pacman:
    name: anki
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [mandarin,anki]

- name: install ibus (aur)
  pacman:
    name:
      - ibus
      # - ibus-qt
      - ibus-libpinyin
      - ibus-rime
      - ibus-m17n
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [mandarin,ibus]

- name: install mandarin fonts (aur)
  pacman:
    name:
      # - adobe-source-han-sans-cn-fonts
      # - adobe-source-han-sans-tw-fonts
      # - adobe-source-han-serif-cn-fonts
      # - adobe-source-han-serif-tw-fonts
      # - wqy-microhei
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [mandarin,fonts]

- name: install taiwan fonts (aur)
  pacaur:
    name: "{{item}}"
  with_items:
    - ttf-tw
  when: ansible_pkg_mgr == "pacman"
  tags: [mandarin,taiwan-fonts]

- name: ibus shell config (aur)
  copy:
    dest: "{{profiledir}}/50-ibus.sh"
    content: |
      export GTK_IM_MODULE=ibus
      export XMODIFIERS=@im=ibus
      export QT_IM_MODULE=ibus
  when: ansible_pkg_mgr == "pacman"
  tags: [mandarin,ibus]
