---

- name: install zsh (pacman)
  pacman: name={{item}}
  with_items:
    - zsh
    - zsh-completions
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,zsh]

- name: install zsh (apt)
  apt: name={{item}}
  with_items:
    - zsh
    - zsh-common
    - zsh-doc
  become: true
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,zsh]

- name: check zprezto repository presence
  stat: path={{ zprezto_dir }}
  register: have_zprezto
  tags: [config-install,zsh,zprezto]

- name: clone zprezto
  git: repo={{ zprezto_repo }}
       dest={{ zprezto_dir }}
       recursive=true
  when: not have_zprezto.stat.exists
  tags: [config-install,zsh,zprezto]

- name: install zprezto
  file: state=link
        src={{ zprezto_dir }}/runcoms/{{item}}
        dest={{ homedir }}/.{{item}}
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc
  tags: [config-install,zsh,zprezto]

- name: create bin dir
  file:
    path: "{{homedir}}/bin"
    state: directory
  tags: [config-install,zsh]

- name: create profile dir
  file: path={{profiledir}} state=directory
  tags: [config-install,zsh]

- name: install base config
  copy: src={{item}}
        dest={{ profiledir }}/{{item | basename}}
  with_fileglob: "*.zsh"
  tags: [config,zsh]
