---

- name: install zsh
  pacaur: name={{item}}
  with_items:
    - zsh
    - zsh-completions
  tags: [config-install,zsh]
  when: ansible_pkg_mgr == "pacman"

- name: check zprezto repository presence
  stat: path={{ zprezto.dir }}
  register: have_zprezto
  tags: [config-install,zsh,zprezto]

- name: clone zprezto
  git: clone=yes
       repo={{ zprezto.repo }}
       dest={{ zprezto.dir }}
       recursive=true
  when: have_zprezto.stat.exists != True
  tags: [config-install,zsh,zprezto]

- name: install zprezto
  file: state=link
        src={{ zprezto.dir }}/runcoms/{{item}}
        dest={{ homedir }}/.{{item}}
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc
  tags: [config-install,zsh,zprezto]

- name: create profile dir
  file: path={{profiledir}} state=directory
  tags: [config-install,zsh]

- name: install base config
  copy: src={{item}}
        dest={{ profiledir }}/{{item | basename}}
  with_fileglob: "*.zsh"
  tags: [config,zsh]

