---
- name: check xcwd
  stat: path={{homedir}}/bin/xcwd
  register: have_xcwd
  tags: [config-install,xcwd,i3]

- name: download xcwd
  git:
    repo: https://github.com/schischi/xcwd.git
    dest: "{{homedir}}/code/xcwd"
    force: true
  when: not have_xcwd.stat.exists
  tags: [config-install,xcwd,i3]

- name: compile xcwd
  command: make
  args:
    chdir:   "{{homedir}}/code/xcwd"
    creates: "{{homedir}}/code/xcwd/xcwd"
  when: not have_xcwd.stat.exists
  tags: [config-install,xcwd,i3]

- name: install xcwd
  command: install "{{homedir}}/code/xcwd/xcwd" "{{homedir}}/bin"
  args:
    creates: "{{homedir}}/bin/xcwd"
  when: not have_xcwd.stat.exists
  tags: [config-install,xcwd,i3]
