---
- name: install (apt)
  apt: name=i3
  become: true
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,i3]

- name: install (arch)
  pacman:
    name: i3-wm
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,i3]

- name: install perl libs (arch)
  pacman:
    name: perl-anyevent-i3
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,i3]

- name: install i3lock (arch)
  pacman:
    name: i3lock
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,i3,i3lock]
