---
- name: install (apt)
  apt: name=i3
  become: true
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,i3]

- name: install (arch)
  pacaur:
    name: i3-wm
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,i3]
