---
- name: check installed
  stat: path={{fzf.binpath}}
  register: have_fzf
  become: "{{target_user}}"
  tags: [config-install,fzf,multiuser]

- name: install
  command: go get {{fzf.package}}
  when: not have_fzf.stat.exists
  environment:
    GOPATH: "{{gopath}}"
  become: "{{target_user}}"
  tags: [config-install,fzf,multiuser]

- name: configure
  template: dest={{profiledir}}/20-fzf.zsh
            src=fzf.zsh
  become: "{{target_user}}"
  tags: [config-install,fzf,multiuser]
