---
- name: check installed
  stat: path={{fzf.binpath}}
  register: have_fzf
  tags: [config-install,fzf]

- name: install
  command: go get {{fzf.package}}
  when: not have_fzf.stat.exists
  tags: [config-install,fzf]
  environment:
    GOPATH: "{{gopath}}"

- name: configure
  template: dest={{profiledir}}/20-fzf.zsh
            src=fzf.zsh
  tags: [config-install,fzf]
