---
# - name: check installed
#   stat: path={{fzf.binpath}}
#   register: have_fzf
#   tags: [config-install,fzf]


- name: install
  ansible.builtin.pacman:
    name: fzf
  tags: [config-install,fzf]
  when: ansible_pkg_mgr == "pacman"

- name: configure
  template: dest={{profiledir}}/20-fzf.zsh
            src=fzf.zsh
  tags: [config-install,fzf]
