---
- name: install git (apt)
  apt: name={{item}}
  with_items:
    - git
    - git-man
  become: true
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,git]

- name: configure gitconfig
  template: dest={{homedir}}/.gitconfig
            src=gitconfig
  tags: [config,git]

- name: configure git credentials
  template: dest={{homedir}}/.git-credentials
            src=git-credentials
            mode=0600
  tags: [config,git]

- name: configure shell $GITHUB_REPO_TOKEN
  copy:
    dest: "{{ profiledir }}/10-github-repo.sh"
    content: |
      export GITHUB_REPO_TOKEN={{github_repo_token}}
    mode: 0600
  tags: [config,git,github]
