---
# - name: install chromium (arch)
#   pacman:
#     name: chromium
#   become: true
#   when: ansible_pkg_mgr == "pacman"
#   tags: [config-install,browser,chromium]

# - name: chromium config (arch)
#   copy:
#     dest: "{{homedir}}/.config/chromium-flags.conf"
#     content: |
#       --force-device-scale-factor=2
#   when: ansible_pkg_mgr == "pacman"
#   tags: [config-install,browser,chromium]

- name: install google chrome (arch)
  pacaur:
    name: google-chrome
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,browser,chrome]

- name: install google chrome launcher (arch)
  copy:
    dest: "{{homedir}}/bin/google-chrome"
    content: |
      #!/bin/sh
      google-chrome-stable "$@"
    mode: "0755"
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,browser,chrome]

- name: chrome config (arch)
  copy:
    dest: "{{homedir}}/.config/chrome-flags.conf"
    content: |
      --force-device-scale-factor=2
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,browser,chrome]

# - name: install firefox (arch)
#   pacman:
#     name:
#       - firefox
#   become: true
#   when: ansible_pkg_mgr == "pacman"
#   tags: [config-install,browser,firefox]
