---

- name: install cli manager (arch)
  pacman:
    name: yubikey-manager
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [yubikey,yubikey-manager]

- name: install yubico authenticator (arch)
  # pacaur:
  #   name: yubico-yubioath-desktop
  debug:
    msg: fix yubico authenticator
  when: ansible_pkg_mgr == "pacman"
  tags: [yubikey,yubico-authenticator]

- name: enable pcscd
  systemd:
    name: pcscd.service
    enabled: yes
    state: started
  when: ansible_service_mgr == "systemd"
  tags: [yubikey]
