---

- name: install cli manager (arch)
  pacman:
    name: yubikey-manager
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [yubikey,yubikey-manager]

- name: configure scdaemon
  lineinfile:
    create: yes
    path: "{{homedir}}/.gnupg/scdaemon.conf"
    line: reader-port Yubico Yubi
  tags: [yubikey]

- name: enable pcscd
  systemd:
    name: pcscd.service
    enabled: yes
    state: started
  become: true
  when: ansible_service_mgr == "systemd"
  tags: [yubikey]
