---

- name: install (apt)
  apt: name=rofi
  become: true
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,rofi]

- name: install (arch)
  pacaur:
    name: rofi
  when: ansible_pkg_mgr == "pacman"
  tags: [rofi]
