---
- name: install (apt)
  apt: name=rofi
  become: true
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,rofi]

- name: install (arch)
  shell: echo install ascii; false
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,rofi]
