---
- name: install node (osx)
  homebrew:
    state: present
    name:
      - node
      - yarn
  when: ansible_pkg_mgr == "homebrew"
  tags: [config-install,nodejs,node]

- name: install node (aur)
  pacman:
    name:
      - nodejs
      - yarn
      - npm
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,nodejs,node]

- name: add yarn bindir to PATH
  copy:
    dest: "{{profiledir}}/50-yarn.sh"
    content: |
      export PATH="$PATH:$HOME/.yarn/bin"
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,nodejs,node]
