---

- name: install ethereum mist
  pacaur:
    name: mist
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,ethereum-dev,mist]

- name: install geth
  pacaur:
    name: go-ethereum
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,ethereum-dev,go-ethereum]

- name: install truffle
  pacaur:
    name: truffle
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,ethereum-dev,truffle]
