---
- name: install keybase
  pacman:
    name: keybase
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [keybase]

- name: install kbfs
  pacman:
    name: kbfs
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [keybase]

- name: install keybase
  pacman:
    name: keybase-gui
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [keybase]
