---
- name: load loop module on startup
  copy:
    dest: "/etc/modules-load.d/loop.conf"
    content: "loop\n"
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,docker]

- name: load loop module
  modprobe:
    name: loop
    state: present
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,docker]

- name: install docker
  pacman:
    name: [docker, docker-compose]
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,docker]

- name: enable docker socket
  systemd:
    name: docker.socket
    enabled: yes
    state: started
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,docker]

- name: add user to docker group
  user:
    append: yes
    groups: docker
    name: "{{ansible_user_id}}"
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,docker]

- name: enable userns
  copy:
    dest: "/etc/sysctl.d/userns.conf"
    content: |
      kernel.unprivileged_userns_clone=1
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,docker]
