---
- name: check golang sources
  stat: path={{ovrclk.sourcedir}}
  register: have_ovrclk
  tags: [config-install,ovrclk]

- name: install golang sources
  git: repo={{ovrclk.repository}}
       dest={{ovrclk.sourcedir}}
       recursive=true
  when: not have_ovrclk.stat.exists
  tags: [config-install,ovrclk]

- name: install shell profile
  template: src=ovrclk.sh
            dest={{ profiledir }}/20-ovrclk.sh
  tags: [config,ovrclk]
