---
- name: install lib dependencies
  apt:
    name: "{{item}}"
  with_items:
    - libssl-dev
    - libreadline-dev
  become: true
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,rbenv]

- name: checkout source
  git:
    repo: https://github.com/rbenv/rbenv.git
    update: no
    dest: "{{homedir}}/.rbenv"
  become: "{{target_user}}"
  tags: [config-install,rbenv,multiuser]

- name: add zsh hook
  copy:
    dest: "{{profiledir}}/50-rbenv.sh"
    content: |
      export PATH="{{homedir}}/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"
  become: "{{target_user}}"
  tags: [config-install,rbenv,multiuser]

- name: install ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    update: no
    dest: "{{homedir}}/.rbenv/plugins/ruby-build"
  become: "{{target_user}}"
  tags: [config-install,rbenv,multiuser]
