---
- name: install neovim (pacman)
  pacman: name={{item}}
  with_items:
    - python-neovim
    - neovim
    - powerline-fonts
  become: true
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,neovim]

- name: install neovim ppa (apt)
  apt_repository: repo=ppa:neovim-ppa/unstable
  become: true
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,neovim]

- name: install neovim (apt)
  apt: name={{item}}
  with_items:
    - neovim
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
  become: true
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,neovim]

- name: install python3-neovim (apt)
  pip: name=neovim
       executable=pip3
       extra_args="--user"
  when: ansible_pkg_mgr == "apt"
  tags: [config-install,neovim]

- name: install neovim (osx)
  homebrew:
    name: "{{item}}"
  with_items:
    - neovim
    - python3
  when: ansible_pkg_mgr == "homebrew"
  tags: [config-install,neovim]

- name: install python-neovim (osx)
  pip:
    name: neovim
    extra_args: --user
  when: ansible_pkg_mgr == "homebrew"
  tags: [config-install,neovim]

- name: install python3-neovim (osx)
  pip:
    executable: pip3
    name: neovim
    extra_args: --user
  when: ansible_pkg_mgr == "homebrew"
  tags: [config-install,neovim]

- name: create directories
  file: path={{item}} state=directory
  with_items:
    - "{{neovim.basedir}}"
    - "{{neovim.confdir}}"
    - "{{neovim.dein.basedir}}"
    - "{{neovim.dein.bundledir}}"
  tags: [config-install,neovim]

- name: check dein install
  stat: path={{neovim.dein.installdir}}
  register: have_dein
  tags: [config-install,neovim,dein]

- name: install dein
  git: repo={{ neovim.dein.repository }}
       dest={{ neovim.dein.installdir }}
  when: not have_dein.stat.exists
  tags: [config-install,neovim,dein]

- name: install init.vim
  template: src=init.vim
            dest={{neovim.basedir}}/init.vim
  tags: [config,neovim]

- name: install conf.d components
  copy: src={{item}}
        dest={{neovim.confdir}}/{{item | basename}}
  with_fileglob:
    - "../files/conf.d/*.nvim"
  tags: [config,neovim]
