---
- name: install fonts
  pacaur:
    name: "{{item}}"
  with_items:
    - ttf-dejavu
    - ttf-font-awesome-4
    - ttf-unifont
    - siji-git
  when: ansible_pkg_mgr == "pacman"
  tags: [config-install,fonts]
